name: Labels
on:
  push:
    branches: [master]
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labels.yml'
jobs:
  labeler:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v3.1.1
